### ISSUE TITLE
No method `packer`

### ISSUE THREAD

**Issue by a-komarev** [DraperStudio/Laravel-Elixir-Packer#1]
```sh
TypeError: Object #<Object> has no method 'packer'
    at /home/ell/development/elixir-packer/gulpfile.js:103:9
    at Elixir (/home/ell/development/elixir-packer/node_modules/laravel-elixir/index.js:3:5)
    at Object.<anonymous> (/home/ell/development/elixir-packer/gulpfile.js:19:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
```

Installation was successful:
```sh
Binary is fine; exiting.
laravel-elixir-packer@1.0.0 node_modules/laravel-elixir-packer
├── underscore@1.8.3
├── filendir@0.0.1 (mkdirp@0.5.1)
├── packer@0.0.6 (htmlparser@1.7.7, nomnom@1.8.1, jsdom@3.1.2)
├── gulp-notify@2.2.0 (lodash.template@3.6.2, node.extend@1.1.5, through2@0.6.5, gulp-util@3.0.6, node-notifier@4.2.3)
└── laravel-elixir@2.3.13 (gulp-rename@1.2.2, install@0.1.8, require-dir@0.1.0, partialify@3.1.5, run-sequence@1.1.2, vinyl-paths@1.0.0, parse-filepath@0.5.0, del@0.1.3, gulp-util@3.0.6, gulp-if@1.2.5, vinyl-buffer@1.0.0, gulp-rev@2.0.1, vinyl-source-stream@1.1.0, gulp-load-plugins@0.7.1, gulp-phpunit@0.6.3, gulp-minify-css@0.3.13, gulp-shell@0.2.11, merge-stream@0.1.8, gulp-filter@1.0.2, gulp-sourcemaps@1.5.2, gulp-concat@2.6.0, gulp-uglify@1.2.0, gulp-ruby-sass@1.0.5, gulp-phpspec@0.4.2, gulp-coffee@2.3.1, gulp-autoprefixer@1.0.1, browserify@9.0.8, gulp-less@3.0.3, watchify@3.3.1, gulp-babel@5.2.0, gulp-notify@1.8.0, gulp-sass@2.0.4, babelify@6.1.3, npm@2.13.3)

```

**Comment by DraperStudio** [comment]
Have it installed in 3 Projects and works just fine.

Did you insert `require('laravel-elixir-packer');` like it is described in the README?

**Comment by a-komarev** [comment]
Yes.
```js
var elixir = require('laravel-elixir');

require('laravel-elixir-css-url-adjuster');
require('laravel-elixir-packer');
```

**Comment by DraperStudio** [comment]
Which Elixir Version do you use? Recently there were some changes to Elixir and Extensions.

**Comment by a-komarev** [comment]
But I can see warns during the npm install process:
```sh
npm WARN engine hawk@3.1.0: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
```
I suppose it could be the problem.

**Comment by DraperStudio** [comment]
Seems like you need to update your npm.

**Comment by DraperStudio** [comment]
Tested it with Elixir 2.0 and works just fine, for Elixir 3.0 use this.

```js
var gulp = require('gulp'),
    packer = require('packer'),
    filendir = require('filendir'),
    _ = require('underscore'),
    notify = require('gulp-notify'),
    fs = require('fs');

var Elixir = require('laravel-elixir');
var Task = Elixir.Task;

Elixir.extend('packer', function(src, dest, options) {
    options = _.extend({
        base62Encode: true,
        shrinkVariables: true,
    }, options);

    new Task('packer', function(callback) {
        var fileContent = fs.readFileSync(src, 'utf8');
        var packedContents = packer.pack(fileContent, options.base62Encode, options.shrinkVariables);

        if (!filendir.ws(dest, packedContents)) {
            return notify({
                title: 'Packer Failed!',
                icon: __dirname + '/../laravel-elixir/icons/fail.png'
            });
        }

        return notify({
            title: 'Packer Succeeded!',
            icon: __dirname + '/../laravel-elixir/icons/pass.png'
        });
    });
});
```

**Comment by DraperStudio** [comment]
I have published 1.1.0 which you can use if you use Elixir `^3.0.0`

`~1.0 = Elixir 2.0`
`~1.1 = Elixir 3.0`

**Comment by a-komarev** [comment]
Thank you. Will try to recheck and provide feedback after system upgrade.

**Comment by a-komarev** [comment]
Shame, I've got `"laravel-elixir": "^1.0.0",`. Need to upgrade it then.

**Comment by DraperStudio** [comment]
Just change it to `^1.1.0, run `npm update` you're done.

**Comment by a-komarev** [comment]
At last, i've made it working.
I'm using package `laravel-elixir-css-url-adjuster` in current project but it's not supported by Elixir > 1.0.
```json
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.9.0",
    "laravel-elixir-css-url-adjuster": "https://github.com/unitedworx/laravel-elixir-css-url-adjuster/tarball/patch-1",
    "laravel-elixir-packer": "^1.1.0"
  },
  "dependencies": {
    "laravel-elixir": "^3.0.0"
  }
}
```
Now everything is working.
